# Generated by Django 3.2.11 on 2022-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Formula', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Molwt', models.FloatField()),
                ('Tfp', models.FloatField()),
                ('Tb', models.FloatField()),
                ('Tc', models.FloatField()),
                ('Pc', models.FloatField()),
                ('Vc', models.FloatField()),
                ('Zc', models.FloatField()),
                ('Omega', models.FloatField()),
                ('Dipm', models.FloatField()),
                ('CpA', models.FloatField()),
                ('CpB', models.FloatField()),
                ('CpC', models.FloatField()),
                ('CpD', models.FloatField()),
                ('dHf', models.FloatField()),
                ('dGf', models.FloatField()),
                ('Eq', models.FloatField()),
                ('VpA', models.FloatField()),
                ('VpB', models.FloatField()),
                ('VpC', models.FloatField()),
                ('VpD', models.FloatField()),
                ('Tmin', models.FloatField()),
                ('Tmax', models.FloatField()),
                ('Lden', models.FloatField()),
                ('Tden', models.FloatField()),
            ],
        ),
    ]
