# Generated by Django 3.2.11 on 2022-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220325_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Eq',
            field=models.IntegerField(null=True),
        ),
    ]
