# Generated by Django 3.2.11 on 2022-03-26 07:34

from django.db import migrations
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_eq'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='CpFigure',
            field=django_matplotlib.fields.MatplotlibFigureField(),
        ),
    ]
